import { App, TFile, TFolder } from 'obsidian';
import { VideoAnalysis } from './ai-categorizer';
import { VideoFile } from './video-scanner';

export class NoteManager {
	private app: App;
	private noteFolder: string;

	constructor(app: App, noteFolder: string) {
		this.app = app;
		this.noteFolder = noteFolder;
	}

	async createNote(video: VideoFile, analysis: VideoAnalysis): Promise<TFile> {
		const noteName = this.sanitizeFileName(video.name);
		const notePath = this.noteFolder === '/' 
			? `${noteName}.md`
			: `${this.noteFolder}/${noteName}.md`;

		const content = this.buildNoteContent(video, analysis);

		const file = await this.app.vault.create(notePath, content);
		return file;
	}

	async noteExists(video: VideoFile): Promise<boolean> {
		const noteName = this.sanitizeFileName(video.name);
		const notePath = this.noteFolder === '/'
			? `${noteName}.md`
			: `${this.noteFolder}/${noteName}.md`;

		const file = this.app.vault.getAbstractFileByPath(notePath);
		return file instanceof TFile;
	}

	getNotePath(video: VideoFile): string {
		const noteName = this.sanitizeFileName(video.name);
		return this.noteFolder === '/'
			? `${noteName}.md`
			: `${this.noteFolder}/${noteName}.md`;
	}

	private sanitizeFileName(name: string): string {
		return name
			.replace(/[<>:"/\\|?*]/g, '')
			.replace(/\s+/g, '-')
			.substring(0, 100);
	}

	private buildNoteContent(video: VideoFile, analysis: VideoAnalysis): string {
		const tags = analysis.tags
			.map(tag => tag.startsWith('#') ? tag : `#${tag}`)
			.join(' ');

		const eventsMarkdown = analysis.events.length > 0
			? analysis.events.map(event => `- **${event.timestamp}**: ${event.description}`).join('\n')
			: 'No events identified';

		return `---
videoPath: "${video.path}"
category: "${analysis.category}"
tags: [${analysis.tags.map(t => `"${t}"`).join(', ')}]
generatedDate: ${new Date().toISOString().split('T')[0]}
videoSize: ${this.formatBytes(video.size)}
videoExtension: "${video.extension}"
---

${tags}

# ${analysis.title}

## Description
${analysis.description}

## Category
${analysis.category}

## Important Events
${eventsMarkdown}

## Metadata
- **File**: ${video.name}${video.extension}
- **Size**: ${this.formatBytes(video.size)}
- **Last Modified**: ${video.mtime.toLocaleDateString()}
- **Generated**: ${new Date().toLocaleString()}

---
*Note generated by Video Categorizer Plugin*
`;
	}

	private formatBytes(bytes: number): string {
		if (bytes === 0) return '0 Bytes';
		const k = 1024;
		const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
		const i = Math.floor(Math.log(bytes) / Math.log(k));
		return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
	}

	async getOrCreateFolder(): Promise<TFolder> {
		if (this.noteFolder === '/') {
			return this.app.vault.getRoot();
		}

		let folder = this.app.vault.getAbstractFileByPath(this.noteFolder) as TFolder | null;
		
		if (!folder) {
			folder = await this.app.vault.createFolder(this.noteFolder);
		}

		return folder;
	}
}
