import { App, TFile, TFolder } from 'obsidian';
import { VideoAnalysis } from './ai-categorizer';
import { VideoFile } from './video-scanner';

export class NoteManager {
	private app: App;
	private noteFolder: string;
	private tagPrefix: string;

	constructor(app: App, noteFolder: string, tagPrefix = 'OVC-') {
		this.app = app;
		this.noteFolder = noteFolder;
		this.tagPrefix = tagPrefix;
	}

	async createNote(video: VideoFile, analysis: VideoAnalysis): Promise<TFile> {
		const noteName = this.sanitizeFileName(video.name);
		const notePath = this.noteFolder === '/'
			? `${noteName}.md`
			: `${this.noteFolder}/${noteName}.md`;

		const content = this.buildNoteContent(video, analysis);

		const file = await this.app.vault.create(notePath, content);
		return file;
	}

	async noteExists(video: VideoFile): Promise<boolean> {
		const noteName = this.sanitizeFileName(video.name);
		const notePath = this.noteFolder === '/'
			? `${noteName}.md`
			: `${this.noteFolder}/${noteName}.md`;

		const file = this.app.vault.getAbstractFileByPath(notePath);
		return file instanceof TFile;
	}

	getNotePath(video: VideoFile): string {
		const noteName = this.sanitizeFileName(video.name);
		return this.noteFolder === '/'
			? `${noteName}.md`
			: `${this.noteFolder}/${noteName}.md`;
	}

	private sanitizeFileName(name: string): string {
		return name
			.replace(/[<>:"/\\|?*]/g, '')
			.replace(/\s+/g, '-')
			.substring(0, 100);
	}

	private formatTag(raw: string): string {
		// Replace spaces with hyphens, strip leading # if present, apply prefix
		const clean = raw.replace(/^#/, '').replace(/\s+/g, '-');
		return `${this.tagPrefix}${clean}`;
	}

	private buildNoteContent(video: VideoFile, analysis: VideoAnalysis): string {
		// Normalize path to forward slashes (safe for YAML without quotes)
		const normalizedPath = video.path.replace(/\\/g, '/');

		const formattedTags = analysis.tags.map(t => this.formatTag(t));

		// YAML frontmatter: tags as a list, no quotes on simple values
		const tagsYaml = formattedTags.map(t => `  - ${t}`).join('\n');

		// Body tags with # prefix
		const tagLine = formattedTags.map(t => `#${t}`).join(' ');

		const eventsMarkdown = analysis.events.length > 0
			? analysis.events.map(e => `- **${e.timestamp}**: ${e.description}`).join('\n')
			: 'No events identified';

		return `---
videoPath: ${normalizedPath}
category: ${analysis.category}
tags:
${tagsYaml}
generatedDate: ${new Date().toISOString().split('T')[0]}
videoSize: ${this.formatBytes(video.size)}
videoExtension: ${video.extension}
---

${tagLine}

# ${analysis.title}

## Description
${analysis.description}

## Category
${analysis.category}

## Important Events
${eventsMarkdown}

## Metadata
- **File**: ${video.name}${video.extension}
- **Size**: ${this.formatBytes(video.size)}
- **Last Modified**: ${video.mtime.toLocaleDateString()}
- **Generated**: ${new Date().toLocaleString()}

---
*Note generated by Obsidian Video Catalogue*
`;
	}

	private formatBytes(bytes: number): string {
		if (bytes === 0) return '0 Bytes';
		const k = 1024;
		const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
		const i = Math.floor(Math.log(bytes) / Math.log(k));
		return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
	}

	async getOrCreateFolder(): Promise<TFolder> {
		if (this.noteFolder === '/') {
			return this.app.vault.getRoot();
		}

		let folder = this.app.vault.getAbstractFileByPath(this.noteFolder) as TFolder | null;

		if (!folder) {
			folder = await this.app.vault.createFolder(this.noteFolder);
		}

		return folder;
	}
}
